# Generated by Django 5.0.6 on 2024-06-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='amount',
            field=models.FloatField(),
        ),
    ]
